# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94c6c0b64efee04f96d77935b9d763a15916e8e3015af23aa819cdd919d530af960e709a4973b8f352f2411c0aafecdd9a4cf786d4232d1ea97a43ba484296eb

test:
  secret_key_base: 719e2a9f4bb13fec19894e1f48d50f342d64d82e3895061b163fe728a97a57fd5cf321550644255d1571b248690dee6c9aaa15b7c69cde4fceb374e2afe910d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
